unsplash:
  base_url: "https://api.unsplash.com/search/photos"
  count: 100
  image_base_path: ".data/images"
  metadata_path: ".data"
queries:
  - "ananas"
  - "baklava"
  - "pizza"
  - "sushi"
  - "pasta"
  - "burger"
  - "salad"
  - "tacos"
  - "ramen"
  - "steak"
