unsplash:
  base_url: "https://api.unsplash.com/search/photos"

pexels:
  base_url: "https://api.pexels.com/v1/search"

image_base_path: ".data/images"
metadata_path: ".data"

queries:
  - "sushi"
  - "pizza"
  - "bread"
